### PR TITLE
UEFI sytem boot fix

### PR DESCRIPTION
**Pull request by polachz**
My VM images are configured to use UEFI boot. Then VFAT module have to be enabled to keep them functional. This fix grant this without **fs_modules_blocklist** custom modification requirement

### CODE REVIEW

**Comment by konstruktoid** [comment]
Which VM images are you using and with which tool?
Need to write some test for this as well.

**Comment by polachz** [comment]
> Which VM images are you using and with which tool?
> Need to write some test for this as well.

I'm use Hyper-V as hypervisor and all my VMs are Generation2 Linux VM with Secure Boot (Microsoft UEFI Certification Authority). The LInux OS is CentOS 8.3. Today I'm try to move the RHEL, becausethe free 16instances programme (RedHat Developer program) seems to be alive now.

**Comment by konstruktoid** [comment]
The PR looks good, as always, but I'll just have to find a way to test this before merge.

**Comment by konstruktoid** [comment]
Thanks!

**Pull request merged**
