### PR TITLE
RHEL compatibility again and better

### PR DESCRIPTION
**Pull request by polachz**
I have modified RPM keys handling to add them only if necessary as you mentioned in my canceled PR.
Plus fixed rpm module call and more logic organization of the EPEL repo install, not at pre but at packagemgmt.yml

To pre I have to add RHEL license refresh, because it can be expired after some time of inactivity (typically template VM image) - just for real RHEL, and tested on my VMs..

### CODE REVIEW

**Comment by konstruktoid** [comment]
Looks good, I'll just have to get a couple of RHEL licenses for testing.

**Comment by polachz** [comment]
Ok. If you can get free RHEL license, go to:

https://developers.redhat.com/

scroll down and find a "Join Red Hat Developer" button.

This Developer program gives to you 16 free licenses :)

**Comment by konstruktoid** [comment]
Finally got me some RHEL8.

A couple of issues:
The `shell:` tasks can be replaced with `command:`.
and
```shell
CRITICAL Idempotence test failed because of the following tasks:
*  => ansible-role-hardening : Update subscription info on RHEL
*  => ansible-role-hardening : Install CodeReady repo for RHEL8
```

**Comment by konstruktoid** [comment]
Will merge and fix idempotence

**Pull request merged**
